create database mascotas;
use mascotas;
CREATE TABLE CUENTA_USUARIO (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre_usuario VARCHAR(40),
  correo_electronico VARCHAR(80) NOT NULL,
  contrasena VARCHAR(255),
  ultimo_acceso DATETIME,
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE ROL (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  descripcion VARCHAR(100),
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE MEMBRESIA_SUBSCRIPCION (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  descripcion VARCHAR(100),
  duracion INT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  beneficios TEXT,
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE ESPECIE (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  descripcion TEXT,
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE CATEGORIA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  descripcion TEXT,
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE ETIQUETA (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL
);
CREATE TABLE PASARELA_PAGO (
  id BIGINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL,
  descripcion VARCHAR(100),
  imagen_qr TEXT,
  estado_registro CHAR(1) NOT NULL
);
CREATE TABLE NUTRICIONISTA (
  id BIGINT UNSIGNED PRIMARY KEY,
  cuenta_usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  nombre VARCHAR(60) NOT NULL,
  especialidad VARCHAR(60),
  telefono VARCHAR(15) NOT NULL,
  colegio_veterinario VARCHAR(40),
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cuenta_usuario_id) REFERENCES CUENTA_USUARIO(id) ON DELETE CASCADE
);
CREATE TABLE REPARTIDOR (
  id BIGINT UNSIGNED PRIMARY KEY,
  cuenta_usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  nombre VARCHAR(60) NOT NULL,
  telefono VARCHAR(15) NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cuenta_usuario_id) REFERENCES CUENTA_USUARIO(id) ON DELETE CASCADE
);
CREATE TABLE USUARIO_ROL (
  id BIGINT UNSIGNED PRIMARY KEY,
  cuenta_usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  rol_id BIGINT UNSIGNED,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cuenta_usuario_id) REFERENCES CUENTA_USUARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (rol_id) REFERENCES ROL(id) ON DELETE SET NULL
);
CREATE TABLE CLIENTE (
  id BIGINT UNSIGNED PRIMARY KEY,
  cuenta_usuario_id BIGINT UNSIGNED NOT NULL UNIQUE,
  nombre VARCHAR(60) NOT NULL,
  telefono VARCHAR(11),
  foto TEXT,
  membresia_subscripcion_id BIGINT UNSIGNED,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cuenta_usuario_id) REFERENCES CUENTA_USUARIO(id) ON DELETE CASCADE,
  FOREIGN KEY (membresia_subscripcion_id) REFERENCES MEMBRESIA_SUBSCRIPCION(id)
);
CREATE TABLE ALERGIA_ESPECIE (
  id BIGINT UNSIGNED PRIMARY KEY,
  especie_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  descripcion TEXT,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (especie_id) REFERENCES ESPECIE(id) ON DELETE CASCADE
);
CREATE TABLE PLATO_COMBINADO (
  id BIGINT UNSIGNED PRIMARY KEY,
  categoria_id BIGINT UNSIGNED,
  especie_id BIGINT UNSIGNED,
  nombre VARCHAR(60) NOT NULL,
  descripcion TEXT,
  precio DECIMAL(10,2) NOT NULL,
  incluye_plato TINYINT(1) NOT NULL,
  es_crudo TINYINT(1) NOT NULL,
  publicado TINYINT(1) NOT NULL,
  imagen TEXT,
  creado_nutricionista TINYINT(1) NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE SET NULL,
  FOREIGN KEY (especie_id) REFERENCES ESPECIE(id) ON DELETE SET NULL
);
CREATE TABLE REGISTRO_MASCOTA (
  id BIGINT UNSIGNED PRIMARY KEY,
  cliente_id BIGINT UNSIGNED NOT NULL,
  especie_id BIGINT UNSIGNED,
  nombre VARCHAR(40) NOT NULL,
  raza VARCHAR(40),
  sexo CHAR(1) NOT NULL,
  cambio_edad DATE NOT NULL,
  edad INT NOT NULL,
  peso DECIMAL(10,2),
  foto TEXT,
  observaciones TEXT,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id) ON DELETE CASCADE,
  FOREIGN KEY (especie_id) REFERENCES ESPECIE(id)
);
CREATE TABLE DIRECCION (
  id BIGINT UNSIGNED PRIMARY KEY,
  cliente_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  referencia VARCHAR(100),
  latitud DECIMAL(10,2) NOT NULL,
  longitud DECIMAL(10,2) NOT NULL,
  es_principal TINYINT(1) NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id)
);
CREATE TABLE ETIQUETA_PLATO (
  id BIGINT UNSIGNED PRIMARY KEY,
  plato_combinado_id BIGINT UNSIGNED NOT NULL,
  etiqueta_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (plato_combinado_id) REFERENCES PLATO_COMBINADO(id) ON DELETE CASCADE,
  FOREIGN KEY (etiqueta_id) REFERENCES ETIQUETA(id) ON DELETE CASCADE
);
CREATE TABLE PREFERENCIA_ALIMENTARIA (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  descripcion TEXT,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE
);
CREATE TABLE DESCRIPCION_ALERGIAS (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  descripcion TEXT NOT NULL,
  fecha DATETIME NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE
);
CREATE TABLE CONDICION_SALUD (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  fecha DATETIME NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE
);
CREATE TABLE ALERGIA_MASCOTA (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  alergia_especie_id BIGINT UNSIGNED,
  severidad VARCHAR(20) NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE,
  FOREIGN KEY (alergia_especie_id) REFERENCES ALERGIA_ESPECIE(id)
);
CREATE TABLE PLATO_PERSONAL (
  id BIGINT UNSIGNED PRIMARY KEY,
  plato_combinado_id BIGINT UNSIGNED NOT NULL,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (plato_combinado_id) REFERENCES PLATO_COMBINADO(id),
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE
);
CREATE TABLE CONSULTA (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  nutricionista_id BIGINT UNSIGNED,
  fecha DATETIME NOT NULL,
  observaciones TEXT,
  recomendaciones TEXT,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE,
  FOREIGN KEY (nutricionista_id) REFERENCES NUTRICIONISTA(id)
);
CREATE TABLE PEDIDO (
  id BIGINT UNSIGNED PRIMARY KEY,
  cliente_id BIGINT UNSIGNED NOT NULL,
  direccion_id BIGINT UNSIGNED,
  fecha DATETIME NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  incluye_plato TINYINT(1) NOT NULL,
  estado VARCHAR(20) NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id) ON DELETE CASCADE,
  FOREIGN KEY (direccion_id) REFERENCES DIRECCION(id)
);
CREATE TABLE DIETA (
  id BIGINT UNSIGNED PRIMARY KEY,
  consulta_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(60) NOT NULL,
  descripcion TEXT NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (consulta_id) REFERENCES CONSULTA(id) ON DELETE CASCADE
);
CREATE TABLE CONTROL_ENTREGA (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL UNIQUE,
  repartidor_id BIGINT UNSIGNED,
  fecha_entrega DATETIME NOT NULL,
  confirmacion_entrega TINYINT(1) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE CASCADE,
  FOREIGN KEY (repartidor_id) REFERENCES REPARTIDOR(id)
);
CREATE TABLE PAGO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL UNIQUE,
  pasarela_pago_id BIGINT UNSIGNED,
  monto DECIMAL(10,2) NOT NULL,
  fecha DATETIME NOT NULL,
  estado VARCHAR(20) NOT NULL,
  referencia_pago VARCHAR(60),
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE CASCADE,
  FOREIGN KEY (pasarela_pago_id) REFERENCES PASARELA_PAGO(id)
);
CREATE TABLE DETALLE_PEDIDO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL,
  plato_combinado_id BIGINT UNSIGNED,
  cantidad INT NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE CASCADE,
  FOREIGN KEY (plato_combinado_id) REFERENCES PLATO_COMBINADO(id)
);
CREATE TABLE PEDIDO_ESPECIALIZADO (
  id BIGINT UNSIGNED PRIMARY KEY,
  pedido_id BIGINT UNSIGNED NOT NULL UNIQUE,
  registro_mascota_id BIGINT UNSIGNED,
  indicaciones_adicionales TEXT,
  frecuencia_cantidad TEXT NOT NULL,
  objetivo_dieta TEXT,
  consulta_nutricionista TINYINT(1) NOT NULL,
  archivo_adicional TEXT,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE CASCADE,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id)
);
CREATE TABLE DETALLE_DIETA (
  id BIGINT UNSIGNED PRIMARY KEY,
  dieta_id BIGINT UNSIGNED NOT NULL,
  plato_combinado_id BIGINT UNSIGNED,
  instruccion TEXT NOT NULL,
  frecuencia VARCHAR(40) NOT NULL,
  FOREIGN KEY (dieta_id) REFERENCES DIETA(id) ON DELETE CASCADE,
  FOREIGN KEY (plato_combinado_id) REFERENCES PLATO_COMBINADO(id)
);
CREATE TABLE RECETA_MEDICA (
  id BIGINT UNSIGNED PRIMARY KEY,
  registro_mascota_id BIGINT UNSIGNED NOT NULL,
  pedido_especializado_id BIGINT UNSIGNED UNIQUE,
  archivo TEXT,
  fecha DATETIME NOT NULL,
  estado_registro CHAR(1) NOT NULL,
  FOREIGN KEY (registro_mascota_id) REFERENCES REGISTRO_MASCOTA(id) ON DELETE CASCADE,
  FOREIGN KEY (pedido_especializado_id) REFERENCES PEDIDO_ESPECIALIZADO(id)
);
ALTER TABLE plato_combinado
ADD COLUMN ingredientes VARCHAR(255) NULL AFTER descripcion;